function safeJson(value) {
  return JSON.stringify(value).replaceAll("<", "\\u003c").replaceAll("</script", "<\\/script");
}

export function renderDashboard({ runId, study, geometry, result = null }) {
  const state = { runId, study, geometry, result };
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Jango / ${runId}</title>
  <style>
    :root{--ink:#161713;--paper:#ece9dd;--signal:#ff4f19;--acid:#d8ff37;--muted:#8c8d83;--line:#3d3e38;--panel:#20211d;--ok:#8de45a;--bad:#ff665c}
    *{box-sizing:border-box}html{background:var(--ink);color:var(--paper);font-family:"Avenir Next Condensed","Gill Sans",sans-serif}body{margin:0;min-height:100vh;background:radial-gradient(circle at 77% 4%,#333325 0,transparent 31%),linear-gradient(135deg,rgba(255,255,255,.025) 25%,transparent 25%) 0 0/18px 18px,var(--ink)}
    body:after{content:"";position:fixed;inset:0;pointer-events:none;opacity:.18;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.19'/%3E%3C/svg%3E")}
    .shell{width:min(1540px,96vw);margin:0 auto;padding:24px 0 52px;position:relative;z-index:1}.mast{display:grid;grid-template-columns:1fr auto;align-items:end;border-bottom:2px solid var(--paper);padding:0 0 16px}.eyebrow,.mono{font-family:"SFMono-Regular","IBM Plex Mono",monospace;text-transform:uppercase;letter-spacing:.14em}.eyebrow{color:var(--acid);font-size:11px}.brand{margin:4px 0 0;font:900 clamp(54px,9vw,138px)/.78 "Arial Narrow","Avenir Next Condensed",sans-serif;letter-spacing:-.075em;text-transform:uppercase}.brand i{font-family:Georgia,serif;font-weight:400;color:var(--signal)}.status{text-align:right}.lamp{display:inline-block;width:11px;height:11px;border-radius:50%;background:var(--acid);box-shadow:0 0 0 5px #d8ff3721,0 0 25px var(--acid);animation:pulse 1.6s infinite}.status strong{display:block;margin-top:9px;font-size:19px;text-transform:uppercase}.status small{color:var(--muted)}
    .hero{display:grid;grid-template-columns:1.35fr .65fr;gap:18px;margin-top:18px}.objective{min-height:224px;background:var(--paper);color:var(--ink);padding:24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden}.objective:after{content:"${String(study.objective.metric).replaceAll("_", " ")}";position:absolute;right:-8px;bottom:-22px;font:900 62px/1 "Arial Narrow",sans-serif;text-transform:uppercase;color:#0000000d;white-space:nowrap}.objective h2{font:400 17px Georgia,serif;margin:0}.objective .target{font:900 clamp(35px,5vw,72px)/.92 "Arial Narrow",sans-serif;text-transform:uppercase;max-width:90%}.objective .contract{display:flex;gap:25px;font-size:12px}.objective .contract b{display:block;font-size:20px}.fingerprint{border:1px solid var(--line);padding:22px;display:flex;flex-direction:column;justify-content:space-between}.fingerprint .hash{font:12px/1.6 "SFMono-Regular",monospace;word-break:break-all;color:var(--muted)}
    .section-title{display:flex;align-items:center;gap:12px;margin:32px 0 12px}.section-title h2{font:400 20px Georgia,serif;font-style:italic;margin:0}.section-title:after{content:"";height:1px;flex:1;background:var(--line)}.flow{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}.node{position:relative;border:1px solid var(--line);background:#20211dea;min-height:140px;padding:18px;overflow:hidden;animation:rise .55s both}.node:nth-child(2){animation-delay:.08s}.node:nth-child(3){animation-delay:.16s}.node:nth-child(4){animation-delay:.24s}.node:nth-child(5){animation-delay:.32s}.node:before{content:"";position:absolute;top:0;left:0;width:100%;height:3px;background:var(--acid);transform-origin:left;animation:sweep 2.8s infinite}.node .n{color:var(--muted);font:10px "SFMono-Regular",monospace}.node h3{text-transform:uppercase;font-size:22px;margin:20px 0 6px}.node p{font-size:12px;color:var(--muted);margin:0}.node .state{position:absolute;right:13px;top:12px;width:7px;height:7px;border-radius:50%;background:var(--ok);box-shadow:0 0 12px var(--ok)}
    .grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.panel{border:1px solid var(--line);background:#20211ddc;padding:18px;min-height:270px}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line)}.metric{background:var(--panel);padding:15px}.metric span{display:block;color:var(--muted);font:9px "SFMono-Regular",monospace;text-transform:uppercase;letter-spacing:.1em}.metric b{font:700 25px "Arial Narrow",sans-serif}.metric em{font:normal 11px "SFMono-Regular",monospace;margin-left:7px}.delta.up{color:var(--ok)}.delta.down{color:var(--signal)}
    .chart{height:210px;display:flex;align-items:flex-end;gap:3px;border-bottom:1px solid var(--line);padding-top:18px}.bar{flex:1;min-width:2px;background:linear-gradient(to top,var(--signal),var(--acid));opacity:.82;transform-origin:bottom;animation:grow .7s both}.constraints{width:100%;border-collapse:collapse;font:12px "SFMono-Regular",monospace}.constraints th{text-align:left;color:var(--muted);font-weight:400;border-bottom:1px solid var(--line);padding:9px 6px}.constraints td{border-bottom:1px solid #3d3e3866;padding:11px 6px}.gate{font-weight:800}.pass{color:var(--ok)}.fail{color:var(--bad)}.events{max-height:245px;overflow:auto;font:11px/1.65 "SFMono-Regular",monospace}.event{display:grid;grid-template-columns:40px 1fr auto;gap:12px;border-bottom:1px dashed #3d3e3866;padding:7px 0}.event time{color:var(--muted)}.footer{display:flex;justify-content:space-between;margin-top:26px;color:var(--muted);font:10px "SFMono-Regular",monospace;text-transform:uppercase;letter-spacing:.08em}
    @keyframes pulse{50%{opacity:.45;transform:scale(.82)}}@keyframes sweep{0%{transform:scaleX(0)}65%,100%{transform:scaleX(1)}}@keyframes rise{from{opacity:0;transform:translateY(16px)}}@keyframes grow{from{transform:scaleY(0)}}
    @media(max-width:900px){.hero,.grid{grid-template-columns:1fr}.flow{grid-template-columns:1fr 1fr}.metric-grid{grid-template-columns:1fr 1fr}.brand{font-size:62px}}@media(max-width:540px){.flow,.metric-grid{grid-template-columns:1fr}.mast{grid-template-columns:1fr}.status{text-align:left;margin-top:15px}}
  </style>
</head>
<body>
<main class="shell">
  <header class="mast"><div><div class="eyebrow">Autonomous engineering / live evidence plane</div><h1 class="brand">JAN<i>G</i>O</h1></div><div class="status"><span class="lamp"></span><strong id="status">${result?.status ?? "running"}</strong><small class="mono">Run ${runId}</small></div></header>
  <section class="hero"><article class="objective"><h2>Chief engineer contract</h2><div class="target">${study.objective.mode} ${String(study.objective.metric).replaceAll("_", " ")}${study.objective.target == null ? "" : ` → ${study.objective.target}`}</div><div class="contract"><span>CONSTRAINTS<b>${study.constraints.length}</b></span><span>BUDGET<b>${study.budget}</b></span><span>SEED<b>${study.seed}</b></span></div></article><aside class="fingerprint"><div><div class="eyebrow">Source geometry</div><h2>${geometry.model_name}</h2><p>${geometry.component_count} OpenVSP components · ${(geometry.size_bytes/1024).toFixed(1)} kB</p></div><div class="hash">SHA-256<br>${geometry.sha256}</div></aside></section>
  <div class="section-title"><h2>Multidisciplinary relay</h2></div><section class="flow" id="flow"></section>
  <div class="section-title"><h2>Design telemetry</h2></div><section class="grid"><article class="panel"><div class="metric-grid" id="metrics"></div></article><article class="panel"><div class="eyebrow">Convergence / incumbent objective</div><div class="chart" id="chart"></div><p class="mono" id="candidate-count">Awaiting candidates</p></article></section>
  <div class="section-title"><h2>Acceptance gate</h2></div><section class="grid"><article class="panel"><table class="constraints"><thead><tr><th>Metric</th><th>Requirement</th><th>Actual</th><th>Gate</th></tr></thead><tbody id="constraints"></tbody></table></article><article class="panel"><div class="eyebrow">Event ledger / polling events.jsonl</div><div class="events" id="events"></div></article></section>
  <footer class="footer"><span>Conceptual/preliminary MDAO · not certification evidence</span><span>Deterministic task-local computation</span></footer>
</main>
<script>
const data=${safeJson(state)};
const domains=[['01','Geometry','OpenVSP parameter space'],['02','Aerodynamics','Polar & induced drag'],['03','Weights','Mass, fuel & payload'],['04','Performance','Field, climb & range'],['05','Verification','Replay & constraint gates']];
document.querySelector('#flow').innerHTML=domains.map(([n,name,desc])=>\`<article class="node"><i class="state"></i><span class="n">DOMAIN / \${n}</span><h3>\${name}</h3><p>\${desc}</p></article>\`).join('');
function renderResult(result){if(!result)return;document.querySelector('#status').textContent=result.status;const keys=['payload_kg','range_km','takeoff_distance_m','climb_rate_mps','cruise_speed_mps','mtow_kg','landing_distance_m','static_margin','max_altitude_m'];document.querySelector('#metrics').innerHTML=keys.map(k=>{const v=result.winner.metrics[k],b=result.baseline.metrics[k],d=result.deltas[k],up=d>=0;return \`<div class="metric"><span>\${k.replaceAll('_',' ')}</span><b>\${v}</b><em class="delta \${up?'up':'down'}">\${up?'+':''}\${d}</em></div>\`}).join('');const c=result.evidence.convergence;const vals=c.map(x=>x.objective),lo=Math.min(...vals),hi=Math.max(...vals);document.querySelector('#chart').innerHTML=c.slice(-90).map((x,i)=>\`<i class="bar" title="candidate \${x.candidate}: \${x.objective}" style="height:\${12+88*(x.objective-lo)/(hi-lo||1)}%;animation-delay:\${i*.008}s"></i>\`).join('');document.querySelector('#candidate-count').textContent=\`\${result.evidence.candidates_evaluated} candidates / \${result.evidence.feasible_candidates} feasible\`;document.querySelector('#constraints').innerHTML=(result.winner.assessment.constraints||[]).map(x=>\`<tr><td>\${x.metric}</td><td>\${x.operator} \${x.value}</td><td>\${typeof x.actual==='number'?x.actual.toFixed(3):x.actual}</td><td class="gate \${x.passed?'pass':'fail'}">\${x.passed?'PASS':'FAIL'}</td></tr>\`).join('')||'<tr><td colspan="4">No explicit constraints</td></tr>'}
renderResult(data.result);
let seen=0;async function poll(){try{const raw=await fetch('events.jsonl?'+Date.now()).then(r=>r.text());const events=raw.trim().split('\\n').filter(Boolean).map(JSON.parse);if(events.length!==seen){seen=events.length;document.querySelector('#events').innerHTML=events.slice(-20).reverse().map(e=>\`<div class="event"><b>#\${String(e.sequence).padStart(3,'0')}</b><span>\${e.type.replaceAll('_',' ')}</span><time>\${e.candidate??''}</time></div>\`).join('');}}catch{}setTimeout(poll,1300)}poll();
</script>
</body></html>`;
}
